run/ab-test/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root "pages#home"
  get "about", to: "pages#about"

  # resources :articles , only: [:show, :index, :new, :create, :edit, :update, :destroy]
  
  resources :articles

  get "signup", to: "users#new"
  
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'

  delete 'logout', to: 'sessions#destroy'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

run/ab-test/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

run/ab-test/app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }

end

run/ab-test/app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  
  has_many :articles, dependent: :destroy

  validates :username, presence: true, 
                      length: { minimum: 3, maximum: 25 }, 
                      uniqueness: { case_sensitive: false }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
                  length: { maximum: 105 }, 
                  uniqueness: { case_sensitive: false },
                  format: { with: VALID_EMAIL_REGEX }

  has_secure_password
  
end

run/ab-test/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to perforn that action..."
      redirect_to login_path
    end
  end



end

run/ab-test/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [ :show, :edit, :update, :destroy ]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
    puts "************* ARTICLE: SHOW *******************"
  end

  def index
    # @articles = Article.all
    @articles = Article.paginate(page: params[:page], per_page: 2)
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end
  
  def create
    # debugger
    @article = Article.new(article_params)
    @article.user = current_user

    if @article.save
      flash[:notice] = "Article was created successfully."
      redirect_to @article
    else
      render :new
    end
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      flash[:notice] = "Article was updated successfully..."
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    puts "**************ARTICLE: DESTROY*****************"
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end

  def require_same_user 
    if current_user != @article.user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own posts..."
      redirect_to @article
    end
  end

end

run/ab-test/app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    redirect_to articles_path if logged_in?
  end

  def about
    
  end

end

run/ab-test/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create

      user = User.find_by(email: params[:session][:email].downcase)
      
      if user && user.authenticate(params[:session][:password])
        session[:user_id] = user.id
        flash[:notice] = "Logged in successfully...."
        redirect_to user
      else
        puts "ERROR"
        flash.now[:alert] = "There was something wrong with your login details..." 
        render :new, status: :unprocessable_entity
      end

  end

  def destroy

    puts "DESTROY"

    session[:user_id] = nil

    flash[:notice] = "Logged out"

    redirect_to root_path, status: 303      # must return 303 to indicate success

  end

end

run/ab-test/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [ :show, :edit, :update, :destroy ]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [ :edit, :update, :destroy ]

  def show
    puts "***************** USER: SHOW ********************"
    @articles = @user.articles.paginate(page: params[:page], per_page: 3)
  end

  def index
    # @users = User.all
    @users = User.paginate(page: params[:page], per_page: 3)

  end

  def new
    @user = User.new
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "User account was updated successfully..."
      redirect_to @user
    else
      render 'edit'
    end
  end

  def create
    # debugger
    @user = User.new(user_params)
    if @user.save 
      session[:user_id] = @user.id
      flash[:notice] = "Wecome to the Alpha Blog [#{@user.username}], you have successfully signed up..."
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "Account and all associated articles successfully deleted..."
    redirect_to articles_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end
  
  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own account..."
      redirect_to @user
    end
  end

end

run/ab-test/app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options={ size: 80 })

    # include MD5 gem, should be part of standard ruby install
    # require 'digest/md5'
      
    # get the email from URL-parameters or what have you and make lowercase
    email_address = user.email.downcase
      
    # create the md5 hash
    hash = Digest::MD5.hexdigest(email_address)

    size = options[:size]
    # compile URL which can be used in <img src="RIGHT_HERE"...
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"

    image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block ")

  end

end

run/ab-test/app/helpers/pages_helper.rb
module PagesHelper
end

run/ab-test/app/views/articles/_article.html.erb
<div class="container">
  <% @articles.each do |article| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-body rounded">
          <div class="card-header fst-italic">
          <% if article.user %>
            by <%= link_to article.user.username, user_path(article.user), class: "text-decoration-none" %>
          <% end %>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success text-decoration-none" %></h5>
            <p class="card-text"><%= truncate(article.description, length: 100) %></p>
            <%= link_to "View", article_path(article), class: "btn btn-outline-success" %>

            <% if logged_in? && ( article.user == current_user || current_user.admin? ) %>

              <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-info" %>

              <%= link_to "Delete this", article_path(article), class: "btn btn-outline-danger", method: :delete, data: { turbo_confirm: "Are you sure?", turbo_method: "delete" } %>
              
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>
              Created <%= time_ago_in_words(article.created_at) %> ago,
              Edited <%= time_ago_in_words(article.updated_at) %> ago              
            </small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

run/ab-test/app/views/articles/_form.html.erb
<div class="row justify-content-center">
  <div class="col-10">
    <%= render 'shared/errors', obj: @article %>
    <%= form_with(model: @article, class: "shadow p-3 mb-3 bg-info rounded", data: {turbo: false}, local: true) do |f| %>

      <div class="form-group row">
        <%= f.label :title, class: "col-2 mb-3 col-form-label text-light" %>
        <div class="col-10">
          <%= f.text_field :title, class:"form-control mb-3 shadow rounded", placeholder: "Title of article..." %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :description, class: "col-2 col-form-label text-light" %>
        <div class="col-10">
          <%= f.text_area :description, rows: 10, class:"form-control shadow rounded", placeholder: "Description of article..." %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.submit class: "btn btn-outline-light btn-lg d-grid gap-2 col-2 mx-auto mt-4" %>
      </div>

    <% end %>

  </div>
</div>

run/ab-test/app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Edit Article</h1>
<%= render 'form' %>

run/ab-test/app/views/articles/index.html.erb
<h1 class="text-center mt-4">Listing All Articles</h1>

<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>

<%= render 'article' %>

<div class="flickr_pagination mb-3">
    <%= will_paginate @articles, :container => false %>
</div>

run/ab-test/app/views/articles/new.html.erb
<h1 class="text-center mt-4">Create a New Article</h1>
<%= render 'form' %>

run/ab-test/app/views/articles/show.html.erb
<h2 class="text-center mt-4"><%= @article.title %></h1>

<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow mb-5 bg-body rounded">
        <div class="card-header fst-italic">
            by <%= @article.user.username if @article.user %>
            <%= link_to gravatar_for(@article.user, size: 80), user_path(@article.user) %>
        </div>
        <div class="card-body">
            <div class="card-text"><%= simple_format(@article.description) %></div>
            <br />
            <% if logged_in? && ( @article.user == current_user || current_user.admin? ) %>
              <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-info" %>
              <%= link_to "Delete this", article_path(@article), class: "btn btn-outline-danger", method: :delete, data: { turbo_confirm: "Are you sure?", turbo_method: "delete" } %>
            <% end %>
        </div>
        <div class="card-footer text-muted">
            <small>
              Created <%= time_ago_in_words(@article.created_at) %> ago,
              Edited <%= time_ago_in_words(@article.updated_at) %> ago              
            </small>
        </div>
      </div>
    </div>
  </div>
</div>

run/ab-test/app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="flex-shrink-0 py-4 bg-dark text-white fixed-bottom">
  <div class="container text-center">
    <small>Copyright &copy; <%= link_to "Alpha Blog", root_path, class: "text-white text-decoration-none" %></small>
  </div>
</footer>

run/ab-test/app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>

run/ab-test/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="d-flex flex-column">
    <%= render partial: "shared/navbar" %>
    <div id=""page-content>
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>